In [1]:
import pandas as pd
import numpy as np


In [2]:
#read the dataset
data = pd.read_csv("50_startups.csv")

In [3]:
data.head(3)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39

In [4]:
#check for null values
data.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [5]:
#Here we should do label encoding as we have 1 column state as textual data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['State'] = le.fit_transform(data['State'])

In [6]:
#Check the State column whether it converted into numericals or not
data

R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.20       136897.80        471784.10      2  192261.83
1   162597.70       151377.59        443898.53      0  191792.06
2   153441.51       101145.55        407934.54      1  191050.39
3   144372.41       118671.85        383199.62      2  182901.99
4   142107.34        91391.77        366168.42      1  166187.94
5   131876.90        99814.71        362861.36      2  156991.12
6   134615.46       147198.87        127716.82      0  156122.51
7   130298.13       145530.06        323876.68      1  155752.60
8   120542.52       148718.95        311613.29      2  152211.77
9   123334.88       108679.17        304981.62      0  149759.96
10  101913.08       110594.11        229160.95      1  146121.95
11  100671.96        91790.61        249744.55      0  144259.40
12   93863.75       127320.38        249839.44      1  141585.52
13   91992.39       135495.07        252664.93      0  134307.35
14  119943.24       156547.42        256512.92      1  132602.65
15  114523.61       122616.84        261776.23      2  129917.04
16   78013.11       121597.55        264346.06      0  126992.93
17   94657.16       145077.58        282574.31      2  125370.37
18   91749.16       114175.79        294919.57      1  124266.90
19   86419.70       153514.11             0.00      2  122776.86
20   76253.86       113867.30        298664.47      0  118474.03
21   78389.47       153773.43        299737.29      2  111313.02
22   73994.56       122782.75        303319.26      1  110352.25
23   67532.53       105751.03        304768.73      1  108733.99
24   77044.01        99281.34        140574.81      2  108552.04
25   64664.71       139553.16        137962.62      0  107404.34
26   75328.87       144135.98        134050.07      1  105733.54
27   72107.60       127864.55        353183.81      2  105008.31
28   66051.52       182645.56        118148.20      1  103282.38
29   65605.48       153032.06        107138.38      2  101004.64
30   61994.48       115641.28         91131.24      1   99937.59
31   61136.38       152701.92         88218.23      2   97483.56
32   63408.86       129219.61         46085.25      0   97427.84
33   55493.95       103057.49        214634.81      1   96778.92
34   46426.07       157693.92        210797.67      0   96712.80
35   46014.02        85047.44        205517.64      2   96479.51
36   28663.76       127056.21        201126.82      1   90708.19
37   44069.95        51283.14        197029.42      0   89949.14
38   20229.59        65947.93        185265.10      2   81229.06
39   38558.51        82982.09        174999.30      0   81005.76
40   28754.33       118546.05        172795.67      0   78239.91
41   27892.92        84710.77        164470.71      1   77798.83
42   23640.93        96189.63        148001.11      0   71498.49
43   15505.73       127382.30         35534.17      2   69758.98
44   22177.74       154806.14         28334.72      0   65200.33
45    1000.23       124153.04          1903.93      2   64926.08
46    1315.46       115816.21        297114.46      1   49490.75
47       0.00       135426.92             0.00      0   42559.73
48     542.05        51743.15             0.00      2   35673.41
49       0.00       116983.80         45173.06      0   14681.40

In [8]:
#split the data into x and y
x=data.iloc[:,0:4].values
y=data.iloc[:,4:5].values

In [9]:
# check x with splitted rows came or not ( first 4 rows)
x

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 2.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 2.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 2.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [1.1994324e+05, 1.5654742e+

In [10]:
#same for y check last column (ie profit) is shoowing or not
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [11]:
#check total how many values are there in State colum
data['State'].max()
#we got 2 means total 3 values are there 0,1,2 it means total 3 categorical values were there is the understanding

2

In [13]:
#perform one hot encoding
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,3:4]).toarray()
x = np.delete(x,3,axis = 1)

x = np.concatenate((z,x), axis = 1)

In [14]:
x.shape

(50, 54)

In [15]:
#split the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 0)


In [16]:
#train your model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
#test your model
y_pred = regressor.predict(x_test)

In [18]:
y_pred

array([[198994.31174266],
       [ 59244.67076035],
       [ 85489.14518463],
       [ 37377.01565787],
       [ 82126.79213822],
       [136233.13423267],
       [ 20217.98290215],
       [159453.94707577],
       [111211.37369771],
       [ 62776.32558301]])

In [19]:
#check for accuracy
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)

In [20]:
accuracy

-3.128204357685193

In [21]:
#Now lets test individual values
y = regressor.predict([[0,0,1,12345,12345,12345]])
y

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 54 is different from 6)

R&D Spend, Administration,MarketSpend as 12345 each then the profit is going to be 53659.9002904